name: The frosty brew CAST 
description: Provide a description here  is a talking discord to create and talk with communities alike.
author: Frostxflame.net

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: owl
  color: green/blue

# Define your inputs here.
inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
